name: Java CI with Maven

on:
  push:
    branches: ["master", "master-2.0"]
  pull_request:
    branches: ["master", "master-2.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        { dir: ['tiny-event-sourcing-lib', 'tiny-event-sourcing-spring-app', 'tiny-event-sourcing-spring-boot-starter', 'tiny-mongo-event-store', 'tiny-mongo-event-store-spring-boot-starter'] }
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_TOKEN }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Deploy Snapshot Version with Maven
      working-directory: ${{ matrix.dir }}
      run: mvn -B clean deploy -P release
