name: Java CI with Maven

on:
  push:
    # branches: ["master", "master-2.0"]
    branches: [ "main" ]
  pull_request:
    # branches: ["master", "master-2.0"]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        #{ dir: ['tiny-event-sourcing-lib', 'tiny-event-sourcing-spring-app', 'tiny-event-sourcing-spring-boot-starter', 'tiny-mongo-event-store', 'tiny-mongo-event-store-spring-boot-starter'] }
        { dir: ['tiny-event-sourcing-spring-app'] }
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      working-directory: ${{ matrix.dir }}
      run: mvn --batch-mode --update-snapshots package
